language: python
python:
    - 2.7

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update -qq
    - if [[ $TRAVIS_PYTHON_VERSION == *"2."* ]]; then sudo apt-get install python-numpy python-scipy; fi
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
    - pip install -e 'git+https://github.com/dgasmith/opt_einsum.git#egg=opt_einsum'
    - pip install -e .[tests]
script:
    - py.test
    - python setup.py egg_info -b.dev sdist --formats gztar
